### ISSUE TITLE
what is the function of convertToGreyScale？

### ISSUE THREAD

**Issue by PrivateThink** [nex3z/tflite-mnist-android#2]
As follow：
`private float convertToGreyScale(int color) {
        return (((color >> 16) & 0xFF) + ((color >> 8) & 0xFF) + (color & 0xFF)) / 3.0f / 255.0f;
    }`

I need your help，thanks！

**Comment by nex3z** [comment]
The image captured from [exportToBitmap()](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/MainActivity.java#L46) is a [RGB](https://en.wikipedia.org/wiki/RGB_color_model)  bitmap, but the classifier was trained on [grey scale](https://en.wikipedia.org/wiki/Grayscale) images ([MNIST](http://yann.lecun.com/exdb/mnist/)). So we need to convert the captured RGB bitmap to grey scale for classification. The color actually doesn't matter for this simple job.

If you look at the dataset, you will also find that the images in the dataset have white stroke on black background. So there is an [invert()](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/MainActivity.java#L49) method that inverts the color of the captured image, which has black stroke on white background.

**Comment by PrivateThink** [comment]
my dataset is chinese images like MNIST ,so can i only change inputs? the code is not change

**Comment by nex3z** [comment]
You can keep the pipeline (input -> classification -> output), but  you will have to design and train your own model for that job. The model trained by [train.py](https://github.com/nex3z/tflite-mnist-android/blob/master/train.py) is designed for MNIST digits classification, which classifies digits from 0 to 9. You will need a bigger model for Chinese character recognition.

**Comment by PrivateThink** [comment]
i design and train your own model for  Chinese character recognition.
when i change .pb to .tflite ,i change failed. he is my command：
`./bazel-bin/tensorflow/contrib/lite/toco/toco    --input_file=han.pb   --input_format=TENSORFLOW_GRAPHDEF  --output_format=TFLITE   --output_file=han.tflite --inference_type=FLOAT   --input_type=FLOAT --input_arrays=image_batch   --output_arrays=output --input_shapes=1,64,64,1 
`
i got a error 

`Total transient array allocated size: 1310720 bytes, theoretical optimal value: 1310720 bytes.
2018-05-10 05:45:36.404199: F tensorflow/contrib/lite/toco/tflite/export.cc:315] Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If you have a custom implementation for them you can disable this error with --allow_custom_ops. Here is a list of operators for which you will need custom implementations: RandomUniform, TensorFlowShape`

so i change the  command:

`./bazel-bin/tensorflow/contrib/lite/toco/toco    --input_file=han.pb   --input_format=TENSORFLOW_GRAPHDEF  --output_format=TFLITE   --output_file=han.tflite --inference_type=FLOAT   --input_type=FLOAT --input_arrays=image_batch      --output_arrays=output --input_shapes=1,64,64,1 --allow_custom_ops=true`

it is Successful.
when i run app ,but i got a error, as follow

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.nex3z.tflitemnist, PID: 22839
                  java.lang.IllegalArgumentException: Invalid handle to Interpreter.
                      at org.tensorflow.lite.NativeInterpreterWrapper.getInputDims(Native Method)
                      at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:82)
                      at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:112)
                      at org.tensorflow.lite.Interpreter.run(Interpreter.java:93)
                      at com.nex3z.tflitemnist.Classifier.classify(Classifier.java:46)
                      at com.nex3z.tflitemnist.MainActivity.onDetectClick(MainActivity.java:53)
                      at com.nex3z.tflitemnist.MainActivity_ViewBinding$1.doClick(MainActivity_ViewBinding.java:41)
                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                      at android.view.View.performClick(View.java:5619)
                      at android.view.View$PerformClick.run(View.java:22295)
                      at android.os.Handler.handleCallback(Handler.java:754)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:163)
                      at android.app.ActivityThread.main(ActivityThread.java:6342)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

The code i changed as follow:
`private static final String MODEL_PATH = "han.tflite";

    private static final int DIM_BATCH_SIZE = 1;
    public static final int DIM_IMG_SIZE_HEIGHT = 64;
    public static final int DIM_IMG_SIZE_WIDTH = 64;
    private static final int DIM_PIXEL_SIZE = 1;
    private static final int CATEGORY_COUNT = 101;`
Could you help me finding what problem is?

**Comment by nex3z** [comment]
TensorFlow Lite supports a subset of TensorFlow operations used in common inference models. A full list of supported operations can be found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md).

As the error of the first command shows, `RandomUniform` and `TensorFlowShape` are not supported by TensorFlow Lite, so `toco` refuses to convert the model.

In the second command, you've added `--allow_custom_ops=true` to override the checking, but did not provide your custom implementation for the unsupported operations. As a result, you got a runtime error.

TensorFlow Lite is still in developer preview. If you have difficulty in building your custom operation implementation, maybe you can try your luck in [TensorFlow Mobile](https://www.tensorflow.org/mobile/mobile_intro), which supports more operations. You can find their differences [here](https://www.tensorflow.org/mobile/). I've also made a similar demo [tfmobile-mnist-android](https://github.com/nex3z/tfmobile-mnist-android).

**Comment by PrivateThink** [comment]
thanks!
